services:
  rest-api:
    image: spaces-rest-service:latest
    build: .
    ports:
      - 3000:3000
    hostname: api-spaces-rest-service
    env_file: .env
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - api-postgresql-redis
  postgresql:
    image: postgres:latest
    ports:
      - 5433:5432
    hostname: db-spaces-rest-service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spaces
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - api-postgresql-redis
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6380:6379
    hostname: cache-spaces-rest-service
    volumes:
      - ./redis:/data
    networks:
      - api-postgresql-redis
networks:
  api-postgresql-redis:
    driver: bridge
